name: CI&CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  DOTNETVERSION: 5.0.x

jobs:
  restore:
    name: Restore
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup .NET (${{ env.NODEVERSION }})
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.NODEVERSION }}
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - name: Restore dependencies
      run: dotnet restore
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [ restore ]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Restore dependencies
      uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - name: Build
      run: dotnet build --no-restore
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Restore dependencies
      uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - name: Test
      run: dotnet test --no-build --verbosity normal
