name: CI&CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  DOTNETVERSION: 5.0.x

jobs:
  restore:
    name: Restore
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET (${{ env.NODEVERSION }})
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.NODEVERSION }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Cache dependecies
      uses: actions/cache@v2
      with:
        path: ./*
        key: ${{ github.sha }}-deps
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [ restore ]
    steps:
    - name: Restore dependecies
      uses: actions/cache@v2
      with:
        path: ./*
        key: ${{ github.sha }}-deps
    - name: Build
      run: dotnet build --no-restore
    - name: Cache build
      uses: actions/cache@v2
      with:
        path: ./*
        key: ${{ github.sha }}-build
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
    - name: Restore build
      uses: actions/cache@v2
      with:
        path: ./*
        key: ${{ github.sha }}-build
    - name: Test
      run: dotnet test --no-build --verbosity normal
